// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL25nbjrnpt7voxy6wJbiGU1JgtRBCkcI',
    appId: '1:670214672771:web:5ff8f560c0d5168ce466b6',
    messagingSenderId: '670214672771',
    projectId: 'pos-system-fe6f1',
    authDomain: 'pos-system-fe6f1.firebaseapp.com',
    storageBucket: 'pos-system-fe6f1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO2bpCzMMEXabEh2JZuBFc3QhWFXS4Kn8',
    appId: '1:670214672771:android:0e0dea1972777836e466b6',
    messagingSenderId: '670214672771',
    projectId: 'pos-system-fe6f1',
    storageBucket: 'pos-system-fe6f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh8-hnsJ0rci-unCett-_t7LODiJehi4k',
    appId: '1:670214672771:ios:bb49bf90992a9bbee466b6',
    messagingSenderId: '670214672771',
    projectId: 'pos-system-fe6f1',
    storageBucket: 'pos-system-fe6f1.appspot.com',
    androidClientId: '670214672771-5h5s49j53i10ucvaiost6k8e01pupi6k.apps.googleusercontent.com',
    iosClientId: '670214672771-gml4cloqbf72j6jaetnnnmnt332lg5kv.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh8-hnsJ0rci-unCett-_t7LODiJehi4k',
    appId: '1:670214672771:ios:bb49bf90992a9bbee466b6',
    messagingSenderId: '670214672771',
    projectId: 'pos-system-fe6f1',
    storageBucket: 'pos-system-fe6f1.appspot.com',
    androidClientId: '670214672771-5h5s49j53i10ucvaiost6k8e01pupi6k.apps.googleusercontent.com',
    iosClientId: '670214672771-gml4cloqbf72j6jaetnnnmnt332lg5kv.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
